version: "3.8"

services:
  #nextjs-web:
  express-api:
    container_name: express-api
    restart: always
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - rabbitmq
      - postgresql-db
    networks:
      - app_network
  postgresql-db:
    container_name: postgresql-db
    restart: always
    build: ./apps/postgresql
    ports:
      - 5432:5432
    networks:
      - app_network
  rabbitmq:
    container_name: rabbitmq
    restart: always
    build: ./apps/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
