version: "3.8"

services:
  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - app_network
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    ports:
      - 3001:3001
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - app_network
  db:
    container_name: db
    restart: always
    build: ./apps/postgresql
    ports:
      - 5432:5432
    networks:
      - app_network
    volumes:
      - db:/app/db/postgresql/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 30s
      timeout: 10s
      retries: 5
  rabbitmq:
    container_name: rabbitmq
    restart: always
    build: ./apps/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app_network

volumes:
  db:
networks:
  app_network:
    external: false
    driver: bridge
